### ISSUE TITLE
More on security?

### ISSUE THREAD

**Issue by JoeMurray** [progressivetech/net.ourpowerbase.remoteform#1]
Thanks for this Jamie...it seems like it could help some of the low-cost implementations we occasionally provide. 

1. Could you indicate if the user experience of Privacy Badger users will include a graceful degradation message indicating that the functionality is not available because of their browser's restrictions?

2. The security vulnerabilities surrounding Profiles being available as cut and paste html that could be used on other sites (https://docs.civicrm.org/user/en/latest/organising-your-data/profiles/#standalone-forms-with-profiles) led to it being removed (see dmaster to confirm). Would you say that the approach of this extension of naming urls that are allowed to post would be sufficient to make HTML snippets adequately secure so that could be added back in? What's the difference between doing this for js vs html, if any?

**Comment by jmcclelland** [comment]
Hi Joe,

I think a graceful degradation if a user's browers is running privacy badger is a great idea. At the moment, I don't have it. I think some simple javascript tests could figure out whether we're being blocked and could provide a generic message, with a hint about checking privacy badger.

As for remote profiles - as I understand it - the class of security problem is entirely dependent on you being logged into your CiviCRM installation and follows a class of attacks known as [cross site forgery request](https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)_Prevention_Cheat_Sheet).

The threat is that you visit a web site that is under the control of a malicious user. They include a form that you want to submit because it seems like a good idea (e.g. maybe it's a petition). The form seems like it is going to submit your name and address to the petition owners, but in fact, the form action URL is pointing to your CiviCRM installation and it is posting to a form that changes important data that is only available to someone who is logged in.

This attack is normally mitigated in CiviCRM by the use of form tokens. CiviCRM won't accept a form submission unless it comes with a random token that is embedded in a form if you display the form properly on CiviCRM. Since the remote attacker has no way to get this token remotely, they are stopped.

However, with CiviCRM profiles, you are expected to submit a form that is loaded on a remote site. So CiviCRM has to disabled the requirement of having a token on profiles, which is the security problem.

This security problem doesn't apply to the remoteform extension because remoteform has two restrictions:

 * It rejects any input if it detects that a user is logged in. This is the real defense. If CiviCRM had a way to set a profile to be: submit if logged out only, that would also mitigate any security problems as well
 * remoteform allows you to specify which external web sites can post via javascript. This doesn't mitigate against a cross site forgery request (since anyone can simply post to the remoteform end point) but it does limit any other javascript-specific vulnerabilities that people could come up with.

**Comment by jmcclelland** [comment]
The privacy badger alert has now been added.
