### ISSUE TITLE
Hookable $extra_js_urls and $extra_js_params ?

### ISSUE THREAD

**Issue by twomice** [progressivetech/net.ourpowerbase.remoteform#35]
Something like this would allow an extension to alter the printed "code to copy", making it easier for the extension to help non-developer site admins to customize the behavior of their Remote Forms:

```
diff --git a/remoteform.php b/remoteform.php
index f5939d0..8f5fc7c 100644
--- a/remoteform.php
+++ b/remoteform.php
@@ -198,6 +198,16 @@ function remoteform_get_displayable_code($id, $entity = 'Profile') {
     }
   }
 
+  $null = NULL;
+  CRM_Utils_Hook::singleton()->invoke(1, $extra_js_urls, $null, $null,
+    $null, $null, $null,
+    'civicrm_remoteform_extraJsUrls'
+  );
+  CRM_Utils_Hook::singleton()->invoke(1, $extra_js_params, $null, $null,
+    $null, $null, $null,
+    'civicrm_remoteform_extraJsParams'
+  );
+
   return 
       htmlentities('<!-- The stylesheet link is optional and can be removed ') . '<br />' .
       htmlentities('if you want to style the form yourself, or if you ') . '<br />' .
```
@jmcclelland  Would such a PR be considered helpful?

**Comment by twomice** [comment]
Just in case: https://github.com/progressivetech/net.ourpowerbase.remoteform/pull/36

**Comment by mlutfy** [comment]
If you don't mind me chiming in: I think this is pretty neat because we often customize the CSS of embedded forms in the client site (but that means that they have to rely on us, which is expensive). Being able to add custom JS would also help with form validation and conditional fields.

Are you sure it's the correct hook format? I'm always confused about the proper CiviCRM way. iirc, there is an "old" and "new" way. Example of what I think is the "new" (as of ~ 2017) way:  
https://civicrm.stackexchange.com/a/30933/39

**Comment by twomice** [comment]
Thanks @mlutfy This is definitely the 'old' way. I'll modify it to the 'new' way once I have concept approval from the project.

**Comment by jmcclelland** [comment]
Yes - love the concept - thanks!

**Comment by twomice** [comment]
OK, I'll work on a better PR. Thanks!

**Comment by twomice** [comment]
Thanks @jmcclelland !
